/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hemendra_activity_systemevent_libs_SystemSleepDetector */

#ifndef _Included_com_hemendra_activity_systemevent_libs_SystemSleepDetector
#define _Included_com_hemendra_activity_systemevent_libs_SystemSleepDetector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hemendra_activity_systemevent_libs_SystemSleepDetector
 * Method:    startScreenLockDetection
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hemendra_activity_systemevent_libs_SystemSleepDetector_startScreenLockDetection
  (JNIEnv *, jobject);

/*
 * Class:     com_hemendra_activity_systemevent_libs_SystemSleepDetector
 * Method:    stopScreenLockDetection
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hemendra_activity_systemevent_libs_SystemSleepDetector_stopScreenLockDetection
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
